#!/bin/sh
# Hecate Daemon container entrypoint.
#
# Generates vm.args from environment variables before starting the release.
# This allows the container to be configured for clustering without
# rebuilding the image.
#
# Environment variables:
#   HECATE_NODE_NAME     — Erlang node name (e.g., hecate@beam00.lab)
#                          If set, uses -name (long names, required for clustering).
#                          If unset, uses -sname hecate (standalone).
#   HECATE_ERLANG_COOKIE — Erlang distribution cookie.
#                          If unset, uses "hecate_cookie" (default).
#   HECATE_CLUSTER_PEERS — Comma-separated peer hostnames (informational, used by app).
#   HECATE_DIST_IFACE    — Erlang tuple to bind distribution to, e.g. {192,168,1,10}.
#                          Required on hosts whose own hostname resolves to a
#                          loopback address (Debian default /etc/hosts puts
#                          $(hostname) at 127.0.1.1) — without this the dist
#                          listener binds loopback-only, invisible from peers.
set -eu

RELEASE_DIR="/app"
VM_ARGS="${RELEASE_DIR}/releases/vm.args.generated"

# Determine node naming
if [ -n "${HECATE_NODE_NAME:-}" ]; then
    NAME_FLAG="-name ${HECATE_NODE_NAME}"
else
    NAME_FLAG="-sname hecate"
fi

COOKIE="${HECATE_ERLANG_COOKIE:-hecate_cookie}"

# Optional: force distribution bind interface. Emit only if set so
# the default (hostname-resolves) behaviour is preserved for hosts
# that don't need it.
if [ -n "${HECATE_DIST_IFACE:-}" ]; then
    DIST_IFACE_FLAG="-kernel inet_dist_use_interface '${HECATE_DIST_IFACE}'"
else
    DIST_IFACE_FLAG=""
fi

# Generate vm.args
cat > "$VM_ARGS" <<EOF
## Generated by entrypoint.sh — do not edit
${NAME_FLAG}
-setcookie ${COOKIE}
${DIST_IFACE_FLAG}
-heart
-mode interactive
-smp auto
+A 64
+P 1048576
+Q 65536
+sbt db
+SDio 32
EOF

# Point release at generated vm.args
export VMARGS_PATH="$VM_ARGS"

exec "${RELEASE_DIR}/bin/hecate" "$@"
